In [1]:
import numpy as np

# Sorting Algorithms
Notes and Implementations

In [2]:
def get_rand_ints(num=50, sort=False):
    int_list = np.random.randint(low=-10, high=100, size=num)
    if sort:
        int_list = np.sort(int_list)
    print(f"Unsorted List:\n{int_list}")
    return int_list.tolist()


## Selection Sort
Walk array and for each place $i$ in the array of size $n$, find the smallest value amongst the other $n-1$ values. If that value is smaller than the $i$, swap. Continue until array is walked. Will sort in place.

Time: $O(n^2)$


In [11]:
num_list = get_rand_ints(15)

for i in range(len(num_list)):
    for j in range(i+1, len(num_list)):
        if num_list[j] < num_list[i]:
            i_val = num_list[i]
            num_list[i] = num_list[j]
            num_list[j] = i_val
            
print(f"Sorted list:\n{np.array(num_list)}")

Unsorted List:
[49 53 33 45 49 -6 -7 -6 65 49 18 75 66 29 98]
Sorted list:
[-7 -6 -6 18 29 33 45 49 49 49 53 65 66 75 98]


## Insertion Sort
Walks array, separating the array into 2 parts: sorted and unsorted. Takes elements from the unsorted portion of the array and moves them to the correct sequential order in the sorted portion of the array. Stops when the unsorted portion is empty. Sorts elements in-place.   

Time: $O(n^2)$

In [10]:
int_list = get_rand_ints(15)

for i in range(1,len(int_list)):
    val = int_list[i]
    ptr = i-1
    while ptr >= 0 and int_list[ptr] > val:
        #need to move value at ptr up to make room for val. Will have value duplicated at ptr and ptr+1 until next iteration
        int_list[ptr+1] = int_list[ptr]
        ptr-=1
    
    #insert val into correct place
    int_list[ptr+1] = val
    
print(f"Sorted List:\n{np.array(int_list)}")

Unsorted List:
[25  4 11 11 88 26 56 75 70 47 93 58 41 27 89]
Sorted List:
[ 4 11 11 25 26 27 41 47 56 58 70 75 88 89 93]


## Bubble Sort
Sweep through array starting at the beginning of the array and swap elements if $n_1 > n_0$. Will need to do $n \times n-1$ passes 

Time: $O(n^2)$

In [14]:
num_list = get_rand_ints(15)

for i in range(len(num_list)):
    for j in range(i+1, len(num_list)):
        if num_list[j] < num_list[i]:
            i_val = num_list[i]
            num_list[i] = num_list[j]
            num_list[j] = i_val
            
print(f"Sorted List:\n{np.array(num_list)}")

Unsorted List:
[ 65  30  82   4  44  18   8  57  44  86  59 -10  22  41   9]
Sorted List:
[-10   4   8   9  18  22  30  41  44  44  57  59  65  82  86]


## Merge Sort
A sorting method that recursively splits the list in-half until lists of size 1 are produced. Then a merge method is called to combine two sorted lists, initially consisting of two single element lists, by looping over the two sublists and inserting into the main list the correct value by order. Sorts elements in-place.  

Time: $O(nlog(n))$

In [15]:
def merge(l, a, b, c):
    '''Combines sorted sub-arrays l[a:b+1] (endpoint exclusive) and l[b+1:c+1] into sorted sub-array l[a:c+1]'''
    #create two lists left, right from main list
    left = l[a:b+1]
    right = l[b+1:c+1]
    n_left = b-a+1
    n_right = c-b
    
    ileft = 0
    iright = 0
    # loop for full range of elements and insert correct value from sublists into main lists in ascending order
    for i in range(a, c+1):
        if left[ileft] <= right[iright]:
            l[i] = left[ileft]
            ileft+=1
        else:
            l[i] = right[iright]
            iright+=1
        
        # if either left or right index is greater than respective list length, 
        #  append remaining values in the other list to main list
        if ileft >= n_left and iright < n_right:
            l[i+1:c+1] = right[iright:]
            break
        elif iright >= n_right and ileft < n_left:
            l[i+1:c+1] = left[ileft:]
            break
    return l

def merge_sort(l, a, c):
    # do nothing when single element list, i.e. a=c
    if a < c:
        mid_pt = (a + c) // 2
        merge_sort(l, a, mid_pt)
        merge_sort(l, mid_pt+1, c)
        merge(l, a, mid_pt, c)
        
int_list = get_rand_ints()
merge_sort(int_list, 0, len(int_list)-1)

print(f"\n Sorted List:\n{np.array(int_list)}")

Unsorted List:
[82 -3 58 -7 75 65 51 24  4 28 63 28 85 19 56 -4 60 49 99 15  0 86 78 19
  4 27 37 86 56 32  7 96 33 19 44  3 59 25 79 30 60 52 81 18 72 22 78 14
 -8  2]

 Sorted List:
[-8 -7 -4 -3  0  2  3  4  4  7 14 15 18 19 19 19 22 24 25 27 28 28 30 32
 33 37 44 49 51 52 56 56 58 59 60 60 63 65 72 75 78 78 79 81 82 85 86 86
 96 99]


## QuickSort 


## Binary Search Insert
Given a sorted list, performs a recursive binary search to find the index to insert a new value and still maintain the ordering

In [2]:
def get_ordered_place(ordered_values, val, left, right) -> int:
    '''Returns index where new val should be inserted in ordered_values to maintain order'''
    # if left crosses right, return valid insert position
    if left > right:
        return left

    mid_pt = (left+right) // 2
    # if midpoint equals value to be inserted midpoint
    if ordered_values[mid_pt] == val:
        return mid_pt

    # value should be inserted in upper half
    if ordered_values[mid_pt] < val:
        return get_ordered_place(ordered_values, val, mid_pt+1, right)
    else:
        # value should be inserted in lower half
        return get_ordered_place(ordered_values, val, left, mid_pt-1)

In [14]:
ordered = get_rand_ints(10, sort=True)
val = 13
ind = get_ordered_place(ordered, val, 0, len(ordered)-1)
ordered.insert(ind, val)
print(f"\n Sorted List With New Value {val}:\n{np.array(ordered)}")

Unsorted List:
[ 1  4 19 27 33 37 41 47 65 85]

 Sorted List With New Value 13:
[ 1  4 13 19 27 33 37 41 47 65 85]
