<a href="https://colab.research.google.com/github/mathfish/LearningTopics/blob/main/Books/PytorchMastery/Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Torch Version  - note course had version 1.10.0+cu111
print(torch.__version__)

2.1.0+cu121


## Tensors

* Tensors have dimensions `ndim`
  * Scalars are 0 dimension
  * Get dimension by `.shape`
* Get value by `.item()`
* Tensors can be random
  * Many NN start with tensors randomly initialized
  * `torch.rand(3, 4)`
  * Can set the random seed in PyTorch as `torch.manual_seed(42)` and only affects the next PyTorch rand statement
* Tensors can be initilized with zeros or ones
  * `torch.zeros(size=...))`
  * `torch.ones(size=...))`
  * Can also create based on another tensor: `torch.zeros_like(another_tensor)` or `ones_like`
  
* Tensors have a data type
  * Can specify using `torch.tensor(..., dtype=torch.float16)`
  * By default is `float32`
  * Can change type of tensor with `.type()`
* Can make a tensor from a range `torch.arange(start=1, end=20, step=2)`
* Other important parameters
  * `device` - cpu or gpu (or apple metal). Tensors must be on the same device
  * `requires_grad` - track gradients with operations
* Main errors associated with Tensors
  * Tensors not right dtype
  * Tensors not right shape
  * Tensors not on the right device

In [3]:
# scalar
scalar = torch.tensor(7)
vector = torch.tensor([7, 7])
matrix = torch.tensor([[7, 8], [9, 10]])
tensor = torch.tensor([[[1, 3], [1, 2]],[[11, 31], [11, 21]]])

In [4]:
# random tensor
random_tensor = torch.rand(size=(3, 4))

In [5]:
# initialized with zeros and ones
zeros = torch.zeros(size=(3, 4))
ones = torch.ones(size=(3, 4))

In [6]:
# tensor from a range
t1 = torch.arange(1, 10, 2)
torch.ones_like(t1)

tensor([1, 1, 1, 1, 1])

In [7]:
# Data types
flt32_tensor = torch.tensor(15) # default is float32
flt16_tensor = flt32_tensor.type(torch.float16)
flt32_tensor.dtype, flt16_tensor.dtype

(torch.int64, torch.float16)

## Tensor Operations

* Includes addition, subtraction, element wise mult, division, and matrix mult / dot product
  * Note: can use `@` for matmul
  * Probably should use `matmul` or `torch.mm` for clarity
* Can use PyTorch functions (`torch.add`) or use direct operations (e.g. +)
* Aggregations: min, max, mean, sum, etc
  * Can be `torch.sum` or on the tensor itself
  * Can also use `argmin` and `argmax`
* Shape Adjustment
  * `.T` for transpose
  * `.reshape` for reshaping a tensor
  * `.view` for reshaping but sharing the same memory as original tensor. So changing the view will change the original tensor
  * `.stack` and based on `dim=...` will either stack tensors together horizontally or vertically
    * Can also use `hstack` and `vstack`
    * vstack = dim=0 but hstack != dim=1
  * `.squeeze` to remove all 1 dimensions removed
  * `unsqueeze` to add single dimension at a target dim
  * `.permute` view of tensor with dimensions permutated / changed by specification

In [8]:
# Python operators
t1 = torch.tensor([1, 2, 3]
                  )
t1 + 10, t1 * 10

(tensor([11, 12, 13]), tensor([10, 20, 30]))

In [9]:
# PyTorch operators
torch.add(t1, 10), torch.mul(t1, 10)

(tensor([11, 12, 13]), tensor([10, 20, 30]))

In [10]:
# Element-wise multiplication
t2 = torch.tensor([3, 4, 5])
m1 = t1 * t2

# matrix mult
m2 = torch.matmul(t1, t2)

m1, m2, t1 @ t2

(tensor([ 3,  8, 15]), tensor(26), tensor(26))

In [11]:
# Aggregations
t1, t1.max().item(), t1.sum().item(), t1.type(torch.float32).mean().item()

(tensor([1, 2, 3]), 3, 6, 2.0)

In [12]:
t1.argmax(), t1.argmin()

(tensor(2), tensor(0))

In [13]:
x = torch.arange(1, 10)

x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [14]:
# Add an extra dimension or change shape in general
x.reshape(3, 3), x.reshape(1, 9)

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [15]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [16]:
# stack tensors
torch.stack([x, x, x], dim=0).shape

torch.Size([3, 9])

In [17]:
torch.stack([x, x, x], dim=1).shape

torch.Size([9, 3])

In [18]:
torch.vstack([x, x, x]).shape

torch.Size([3, 9])

In [26]:
# Squeezing and Unsqueezing
out = torch.tensor([[[4, 5],[2, 5]]])
out_sq = out.squeeze()
out.shape, out_sq.shape

(torch.Size([1, 2, 2]), torch.Size([2, 2]))

In [25]:
out.shape, out_sq.shape, out_sq.unsqueeze(dim=0).shape, out_sq.unsqueeze(dim=1).shape

(torch.Size([1, 2, 2]),
 torch.Size([2, 2]),
 torch.Size([1, 2, 2]),
 torch.Size([2, 1, 2]))

In [27]:
# permute
xx = torch.rand(size=(224, 224, 3)) # [height, width, color channel]
xx_perm = xx.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

xx.shape, xx_perm.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### Selecting Data in a Tensor
* Indexing
  * x[0, 0] is the same as x[0][0]
  * Indexing is going into each dimension
  * Can use `:` for all items in a dimension
* PyTorch Tensors and Numpy
  * `torch.from_numpy(ndarray)`
  * `torch.Tensor.numpy()` to get numpy ndarray from Tensor
  * Torch will create tensor as float64 when converting from numpy and will be float32 when you go from Tensor to numpy, by default
  

### Device Use
* Can run `!nvidia-smi` to see GPU type if you are using a GPU for device
* `torch.cuda.is_available()` Check for GPU access by PyTorch
* Device agnostic code
  * You may not always have access to a GPU
  * But if available, you want to use it
  * `device = "cuda" if torch.cuda.is_available() else "cpu"`
  * Can also count the number of gpus as `torch.cuda.device_count()`
  * Can use `Tensor.to(device)` to set up device on existing tensor
  * Numpy arrays must be on cpu -> `tensor_gpu.numpy()` will give error. Need to move to cpu first by calling `.cpu()` on tensor
* Can also use multiple GPUs

In [1]:
!nvidia-smi

Thu Feb 22 12:25:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
torch.cuda.is_available()

True

In [4]:
# putting tensors and models on the gpu
device = "cuda" if torch.cuda.is_available() else "cpu"

In [6]:
tensor_cpu = torch.tensor([1, 2, 3], device="cpu")

tensor_cpu, tensor_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [8]:
tensor_gpu = tensor_cpu.to(device)

tensor_gpu.device, tensor_cpu.device

(device(type='cuda', index=0), device(type='cpu'))

In [10]:
tensor_cpu_again = tensor_gpu.cpu()

tensor_cpu_again.device, tensor_gpu.device

(device(type='cpu'), device(type='cuda', index=0))